/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.List;
import java.util.logging.Level;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import controller.BeneficiarioController;
import controller.PensaoController;
import model.Beneficiario;
import model.Pagamento;
import model.Pensao;
import model.enums.EstadoCivil;
import model.enums.EstadoPensao;
import model.enums.FormaPagamento;
import model.enums.Genero;
import model.enums.TipoPensao;
import org.hibernate.HibernateException;

/**
 *
 * @author lpaul
 */
public class telaPricipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaPricipal.class.getName());
    private final BeneficiarioController beneficiarioController = new BeneficiarioController();
    private final PensaoController pensaoController = new PensaoController();
    private Long beneficiarioSelecionadoId;
    private Long pensaoSelecionadaId;

    /**
     * Creates new form telaPricipal
     */
    public telaPricipal() {
        initComponents();
        inicializarCrudBeneficiarios();
        inicializarCrudPensoes();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evento) {
                persistence.HibernateUtil.encerrar();
            }
        });
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        ((CardLayout) centro.getLayout()).show(centro, "card3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabesalho = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        beneficios = new javax.swing.JButton();
        btnPensao = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        centro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        beneficio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        pensao = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1900, 9700));

        cabesalho.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout cabesalhoLayout = new javax.swing.GroupLayout(cabesalho);
        cabesalho.setLayout(cabesalhoLayout);
        cabesalhoLayout.setHorizontalGroup(
            cabesalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1532, Short.MAX_VALUE)
        );
        cabesalhoLayout.setVerticalGroup(
            cabesalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        getContentPane().add(cabesalho, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        Menu.setBackground(new java.awt.Color(0, 102, 0));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("inicio");

        beneficios.setBackground(new java.awt.Color(0, 102, 0));
        beneficios.setForeground(new java.awt.Color(255, 255, 255));
        beneficios.setText("Beneficios");
        beneficios.addActionListener(this::beneficiosActionPerformed);

        btnPensao.setBackground(new java.awt.Color(0, 102, 0));
        btnPensao.setForeground(new java.awt.Color(255, 255, 255));
        btnPensao.setText("pensao");
        btnPensao.addActionListener(this::btnPensaoActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 102, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("pagamentos");

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("relatorio");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beneficios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPensao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(beneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPensao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        centro.setLayout(new java.awt.CardLayout());

        jLabel2.setText("inicial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel2)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        centro.add(jPanel1, "card2");

        beneficio.setBackground(new java.awt.Color(255, 255, 255));
        beneficio.setPreferredSize(new java.awt.Dimension(1900, 903));

        jPanel2.setBackground(new java.awt.Color(0,102,51,150));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 51), 1, true)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("cadastro de beneficios");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 36, 268, -1));

        jButton6.setBackground(new java.awt.Color(0, 102, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("pesquisar");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jButton6.setBorder(null);
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 80, 130, 37));

        jButton7.setBackground(new java.awt.Color(0, 102, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("salvar");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 145, 38));

        jButton8.setBackground(new java.awt.Color(0, 102, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("limpar");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 126, 38));

        jButton9.setBackground(new java.awt.Color(0, 102, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Eliminar");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 128, 42));

        jPanel8.setBackground(new java.awt.Color(0, 102, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("cadastrar dados");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1510, 40));

        jPanel9.setBackground(new java.awt.Color(232,245,233));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nome completo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("n.BI");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Data de nascimeto");

        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jTextField3.setToolTipText("Formato: AAAA-MM-DD");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("sexo");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("estado civil");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("nacionalidade");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("telefone");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Morada");

        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moçambicana" }));
        jComboBox1.setEditable(true);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(
                java.util.Arrays.stream(Genero.values()).map(Enum::name).toArray(String[]::new)));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(
                java.util.Arrays.stream(EstadoCivil.values()).map(Enum::name).toArray(String[]::new)));
        jComboBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel21.setText("NUIT");

        jLabel22.setText("Província");

        jLabel23.setText("Distrito");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)))
                .addGap(52, 52, 52)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 1510, 260));

        jPanel11.setBackground(new java.awt.Color(232, 245, 233));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        jPanel10.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1873, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jTable2.setModel(new DefaultTableModel(
                new Object[0][0],
                new String[] {"ID", "Nome", "BI", "Data de nascimento", "Telefone", "Email", "Nacionalidade"}
        ) {
            @Override
            public boolean isCellEditable(int linha, int coluna) {
                return false;
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 1500, 330));

        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204)));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 390, 40));

        javax.swing.GroupLayout beneficioLayout = new javax.swing.GroupLayout(beneficio);
        beneficio.setLayout(beneficioLayout);
        beneficioLayout.setHorizontalGroup(
            beneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beneficioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        beneficioLayout.setVerticalGroup(
            beneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, beneficioLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        centro.add(beneficio, "card3");

        pensao.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("pensao");

        jLabel17.setText("gerecie os tipos de pensao e beneficios");

        jPanel12.setBackground(new java.awt.Color(232, 245, 233));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Tipo de pensão");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
                java.util.stream.Stream.concat(
                        java.util.stream.Stream.of("Todos"),
                        java.util.Arrays.stream(TipoPensao.values()).map(Enum::name))
                        .toArray(String[]::new)));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Pensionista (ID)");

        jButton2.setText("Novo");
        jButton2.setToolTipText("Iniciar o registo de uma nova pensão (Ctrl+N)");
        jButton2.addActionListener(this::jButton2PensaoActionPerformed);

        jButton10.setText("Guardar");
        jButton10.addActionListener(this::jButton10PensaoActionPerformed);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Estado");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(
                java.util.stream.Stream.concat(
                        java.util.stream.Stream.of("Todos"),
                        java.util.Arrays.stream(EstadoPensao.values()).map(Enum::name))
                        .toArray(String[]::new)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addGap(66, 66, 66)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(232, 245, 233));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("lista de pensoes");

        jTable1.setModel(new DefaultTableModel(
                new Object[0][0],
                new String[] {"ID", "Processo", "Pensionista (ID)", "Tipo",
                    "Estado", "Valor mensal", "Início", "Fim"}
        ) {
            @Override
            public boolean isCellEditable(int linha, int coluna) {
                return false;
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 255, 102));
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTable1.setSelectionForeground(new java.awt.Color(0, 153, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        jLabel15.setText("Pensionista (ID)");

        jLabel24.setText("Valor mensal");

        jLabel25.setText("observacao");

        jTextField14.addActionListener(this::jTextField14ActionPerformed);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(
                java.util.Arrays.stream(EstadoPensao.values()).map(Enum::name).toArray(String[]::new)));

        jLabel26.setText("Número do processo");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(
                java.util.Arrays.stream(TipoPensao.values()).map(Enum::name).toArray(String[]::new)));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox10.setEditable(true);
        jComboBox10.addActionListener(this::jComboBox10ActionPerformed);

        jLabel27.setText("Estado");

        jLabel28.setText("Data de início (AAAA-MM-DD)");

        jLabel29.setText("Tipo");
        jTextField16.setToolTipText("Número único do processo da pensão");
        jTextField13.setToolTipText("Valor mensal em meticais");
        jTextField17.setToolTipText("Formato: AAAA-MM-DD");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(428, 428, 428)
                                .addComponent(jLabel27))
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField16)
                                .addComponent(jComboBox6, 0, 455, Short.MAX_VALUE)))
                        .addGap(120, 120, 120)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox8, 0, 440, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)))
                    .addComponent(jTextField17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel15)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(12, 12, 12)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout pensaoLayout = new javax.swing.GroupLayout(pensao);
        pensao.setLayout(pensaoLayout);
        pensaoLayout.setHorizontalGroup(
            pensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pensaoLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(pensaoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pensaoLayout.setVerticalGroup(
            pensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pensaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        centro.add(pensao, "card4");

        jLabel1.setText("relatorio");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        centro.add(jPanel5, "card5");

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficiosActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) centro.getLayout();
    cl.show(centro, "card3");
    }//GEN-LAST:event_beneficiosActionPerformed

    private void btnPensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPensaoActionPerformed
        // TODO add your handling code here:
          CardLayout cl = (CardLayout) centro.getLayout();
    cl.show(centro, "card4");
    }//GEN-LAST:event_btnPensaoActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (beneficiarioSelecionadoId == null) {
            JOptionPane.showMessageDialog(this, "Selecione um beneficiário na tabela.");
            return;
        }
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Eliminar o beneficiário selecionado?", "Confirmar eliminação",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }
        executarAcaoCrud(() -> {
            if (beneficiarioController.remover(beneficiarioSelecionadoId)) {
                carregarTabela("");
                limparFormularioBeneficiario();
                JOptionPane.showMessageDialog(this, "Beneficiário eliminado.");
            } else {
                JOptionPane.showMessageDialog(this, "O beneficiário já não existe.");
            }
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        limparFormularioBeneficiario();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        executarAcaoCrud(() -> carregarTabela(jTextField4.getText()));
    }

    private void jButton2PensaoActionPerformed(java.awt.event.ActionEvent evento) {
        limparFormularioPensao();
    }

    private void filtrarPensoes(java.awt.event.ActionEvent evento) {
        executarAcaoPensao(() -> {
            String pensionistaTexto = jTextField5.getText().trim();
            Long pensionistaId = null;
            if (!pensionistaTexto.isEmpty()) {
                try {
                    pensionistaId = Long.valueOf(pensionistaTexto);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "O filtro de pensionista aceita apenas o respetivo ID.",
                            "Filtro inválido", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            String tipo = "Todos".equals(jComboBox2.getSelectedItem())
                    ? null : (String) jComboBox2.getSelectedItem();
            String estado = "Todos".equals(jComboBox5.getSelectedItem())
                    ? null : (String) jComboBox5.getSelectedItem();
            carregarTabelaPensoes("", tipo, estado, pensionistaId);
        });
    }

    private void jButton10PensaoActionPerformed(java.awt.event.ActionEvent evento) {
        executarAcaoPensao(() -> {
            TipoPensao tipo = TipoPensao.valueOf((String) jComboBox8.getSelectedItem());
            Long pensionistaId = Long.valueOf(
                    String.valueOf(jComboBox10.getEditor().getItem()).trim());
            Pensao guardada = pensaoController.guardar(
                    pensaoSelecionadaId,
                    jTextField16.getText(),
                    tipo,
                    pensionistaId,
                    new BigDecimal(jTextField13.getText().trim()),
                    LocalDate.parse(jTextField17.getText().trim()),
                    jTextField14.getText());
            limparFormularioPensao();
            carregarTabelaPensoes("", null, null, null);
            atualizarResumoPensoes();
            JOptionPane.showMessageDialog(this,
                    "Pensão guardada com o ID " + guardada.getId() + ".");
        });
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        executarAcaoCrud(() -> {
            Beneficiario guardado = beneficiarioController.guardar(
                    beneficiarioSelecionadoId,
                    jTextField1.getText(),
                    jTextField2.getText(),
                    jTextField6.getText(),
                    jTextField3.getText(),
                    (String) jComboBox3.getSelectedItem(),
                    (String) jComboBox4.getSelectedItem(),
                    jTextField7.getText(),
                    jTextField8.getText(),
                    jTextField9.getText(),
                    String.valueOf(jComboBox1.getEditor().getItem()),
                    jTextField10.getText(),
                    jTextField11.getText());
            carregarTabela("");
            limparFormularioBeneficiario();
            JOptionPane.showMessageDialog(this,
                    "Beneficiário guardado com o ID " + guardado.getId() + ".");
        });
    }

    private void inicializarCrudBeneficiarios() {
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.getSelectionModel().addListSelectionListener(evento -> {
            if (!evento.getValueIsAdjusting() && jTable2.getSelectedRow() >= 0) {
                carregarBeneficiarioSelecionado();
            }
        });
        executarAcaoCrud(() -> carregarTabela(""));
    }

    private void inicializarCrudPensoes() {
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jComboBox6.setEnabled(false);
        jTextField5.addActionListener(this::filtrarPensoes);
        jComboBox2.addActionListener(this::filtrarPensoes);
        jComboBox5.addActionListener(this::filtrarPensoes);
        jTable1.getSelectionModel().addListSelectionListener(evento -> {
            if (!evento.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                carregarPensaoSelecionada();
            }
        });

        JPopupMenu menuPensao = new JPopupMenu();
        adicionarAcaoPensao(menuPensao, "Nova pensão (Ctrl+N)", this::limparFormularioPensao);
        menuPensao.addSeparator();
        adicionarAcaoPensao(menuPensao, "Aprovar", () -> alterarEstadoPensao("aprovar"));
        adicionarAcaoPensao(menuPensao, "Suspender", () -> alterarEstadoPensao("suspender"));
        adicionarAcaoPensao(menuPensao, "Reativar", () -> alterarEstadoPensao("reativar"));
        adicionarAcaoPensao(menuPensao, "Cancelar", () -> alterarEstadoPensao("cancelar"));
        adicionarAcaoPensao(menuPensao, "Arquivar", () -> alterarEstadoPensao("arquivar"));
        menuPensao.addSeparator();
        adicionarAcaoPensao(menuPensao, "Registar pagamento mensal", this::registarPagamentoPensao);
        adicionarAcaoPensao(menuPensao, "Consultar pagamentos", this::consultarPagamentosPensao);
        menuPensao.addSeparator();
        adicionarAcaoPensao(menuPensao, "Eliminar", this::eliminarPensaoSelecionada);
        jTable1.setComponentPopupMenu(menuPensao);
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evento) {
                selecionarLinhaContextual(evento);
            }

            @Override
            public void mouseReleased(MouseEvent evento) {
                selecionarLinhaContextual(evento);
            }

            private void selecionarLinhaContextual(MouseEvent evento) {
                if (evento.isPopupTrigger()) {
                    int linha = jTable1.rowAtPoint(evento.getPoint());
                    if (linha >= 0 && !jTable1.isRowSelected(linha)) {
                        jTable1.setRowSelectionInterval(linha, linha);
                    }
                }
            }
        });
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke("control N"), "novaPensao");
        getRootPane().getActionMap().put("novaPensao", new AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evento) {
                limparFormularioPensao();
            }
        });
        limparFormularioPensao();
        executarAcaoPensao(() -> {
            carregarTabelaPensoes("", null, null, null);
            atualizarResumoPensoes();
        });
    }

    private void adicionarAcaoPensao(JPopupMenu menu, String texto, Runnable acao) {
        JMenuItem item = new JMenuItem(texto);
        item.addActionListener(evento -> executarAcaoPensao(acao));
        menu.add(item);
    }

    private void carregarTabelaPensoes(
            String criterio, String tipo, String estado, Long pensionistaId) {
        List<Pensao> pensoes = pensaoController.pesquisar(criterio, tipo, estado, pensionistaId);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        pensaoSelecionadaId = null;
        modelo.setRowCount(0);
        for (Pensao pensao : pensoes) {
            modelo.addRow(new Object[] {
                pensao.getId(),
                pensao.getNumeroProcesso(),
                pensao.getPensionistaId(),
                pensao.getTipo(),
                pensao.getEstado(),
                pensao.getValorMensal(),
                pensao.getDataInicio(),
                pensao.getDataFim()
            });
        }
    }

    private void carregarPensaoSelecionada() {
        int linha = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
        Long id = ((Number) jTable1.getModel().getValueAt(linha, 0)).longValue();
        executarAcaoPensao(() -> pensaoController.buscarPorId(id).ifPresent(pensao -> {
            pensaoSelecionadaId = pensao.getId();
            jTextField16.setText(pensao.getNumeroProcesso());
            jComboBox10.getEditor().setItem(String.valueOf(pensao.getPensionistaId()));
            jComboBox8.setSelectedItem(pensao.getTipo().name());
            jTextField13.setText(pensao.getValorMensal().toPlainString());
            jComboBox6.setSelectedItem(pensao.getEstado().name());
            jTextField17.setText(pensao.getDataInicio().toString());
            jTextField14.setText(pensao.getObservacoes());
            jComboBox8.setEnabled(false);
        }));
    }

    private void limparFormularioPensao() {
        pensaoSelecionadaId = null;
        jTable1.clearSelection();
        jTextField16.setText("");
        jComboBox10.getEditor().setItem("");
        jComboBox8.setEnabled(true);
        jComboBox8.setSelectedIndex(0);
        jComboBox6.setSelectedItem(EstadoPensao.PENDENTE.name());
        jTextField13.setText("");
        jTextField17.setText(LocalDate.now().toString());
        jTextField14.setText("");
    }

    private void alterarEstadoPensao(String acao) {
        if (pensaoSelecionadaId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma pensão na tabela.");
            return;
        }
        executarAcaoPensao(() -> {
            switch (acao) {
                case "aprovar" -> pensaoController.aprovar(pensaoSelecionadaId);
                case "suspender" -> pensaoController.suspender(pensaoSelecionadaId);
                case "reativar" -> pensaoController.reativar(pensaoSelecionadaId);
                case "cancelar" -> {
                    int confirmacao = JOptionPane.showConfirmDialog(this,
                            "Cancelar a pensão selecionada?", "Confirmar cancelamento",
                            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if (confirmacao != JOptionPane.YES_OPTION) {
                        return;
                    }
                    pensaoController.cancelar(pensaoSelecionadaId);
                }
                case "arquivar" -> pensaoController.arquivar(pensaoSelecionadaId);
                default -> throw new IllegalArgumentException("Ação de pensão desconhecida.");
            }
            carregarTabelaPensoes("", null, null, null);
            atualizarResumoPensoes();
            limparFormularioPensao();
        });
    }

    private void eliminarPensaoSelecionada() {
        if (pensaoSelecionadaId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma pensão na tabela.");
            return;
        }
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Eliminar a pensão selecionada?", "Confirmar eliminação",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmacao == JOptionPane.YES_OPTION) {
            executarAcaoPensao(() -> {
                pensaoController.remover(pensaoSelecionadaId);
                carregarTabelaPensoes("", null, null, null);
                atualizarResumoPensoes();
                limparFormularioPensao();
            });
        }
    }

    private void registarPagamentoPensao() {
        if (pensaoSelecionadaId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma pensão na tabela.");
            return;
        }
        String periodoTexto = JOptionPane.showInputDialog(this,
                "Mês de referência (AAAA-MM):", YearMonth.now().toString());
        if (periodoTexto == null) {
            return;
        }
        String forma = (String) JOptionPane.showInputDialog(this,
                "Forma de pagamento:", "Registar pagamento",
                JOptionPane.QUESTION_MESSAGE, null,
                java.util.Arrays.stream(FormaPagamento.values()).map(Enum::name).toArray(String[]::new),
                FormaPagamento.TRANSFERENCIA_BANCARIA.name());
        if (forma == null) {
            return;
        }
        executarAcaoPensao(() -> {
            Pagamento pagamento = pensaoController.registarPagamento(
                    pensaoSelecionadaId,
                    YearMonth.parse(periodoTexto.trim()),
                    FormaPagamento.valueOf(forma));
            JOptionPane.showMessageDialog(this,
                    "Pagamento de " + pagamento.getValor().toPlainString()
                    + " MZN registado para " + pagamento.getDataReferencia().getYear()
                    + "-" + String.format("%02d", pagamento.getDataReferencia().getMonthValue()) + ".");
        });
    }

    private void consultarPagamentosPensao() {
        if (pensaoSelecionadaId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma pensão na tabela.");
            return;
        }
        executarAcaoPensao(() -> {
            List<Pagamento> pagamentos = pensaoController.listarPagamentos(pensaoSelecionadaId);
            if (pagamentos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ainda não há pagamentos registados.");
                return;
            }
            StringBuilder historico = new StringBuilder();
            for (Pagamento pagamento : pagamentos) {
                historico.append(pagamento.getDataReferencia())
                        .append(" | ")
                        .append(pagamento.getValor().toPlainString())
                        .append(" MZN | ")
                        .append(pagamento.getFormaPagamento())
                        .append(" | ")
                        .append(pagamento.getEstado())
                        .append(System.lineSeparator());
            }
            JOptionPane.showMessageDialog(this, historico.toString(),
                    "Pagamentos da pensão", JOptionPane.INFORMATION_MESSAGE);
        });
    }

    private void atualizarResumoPensoes() {
        jLabel17.setText("Pensões ativas: "
                + pensaoController.calcularTotalMensalAtivo().toPlainString()
                + " MZN/mês | Ctrl+N: nova | clique direito na tabela: operações");
    }

    private void executarAcaoPensao(Runnable acao) {
        try {
            acao.run();
        } catch (IllegalArgumentException | DateTimeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Dados da pensão inválidos", JOptionPane.WARNING_MESSAGE);
        } catch (java.util.NoSuchElementException | IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Operação de pensão não permitida", JOptionPane.WARNING_MESSAGE);
        } catch (HibernateException ex) {
            logger.log(Level.SEVERE, "Falha ao aceder às pensões.", ex);
            JOptionPane.showMessageDialog(this,
                    "Não foi possível aceder à base de dados: " + ex.getMessage(),
                    "Erro de persistência", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarTabela(String criterio) {
        List<Beneficiario> beneficiarios = beneficiarioController.pesquisar(criterio);
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        beneficiarioSelecionadoId = null;
        modelo.setRowCount(0);
        for (Beneficiario beneficiario : beneficiarios) {
            Object[] linha = {
                beneficiario.getId(),
                beneficiario.getNomeCompleto(),
                beneficiario.getNumeroBI(),
                beneficiario.getDataNascimento(),
                beneficiario.getTelefone(),
                beneficiario.getEmail(),
                beneficiario.getNacionalidade()
            };
            modelo.addRow(linha);
        }
    }

    private void carregarBeneficiarioSelecionado() {
        int linha = jTable2.convertRowIndexToModel(jTable2.getSelectedRow());
        Long id = ((Number) jTable2.getModel().getValueAt(linha, 0)).longValue();
        executarAcaoCrud(() -> beneficiarioController.buscarPorId(id).ifPresent(beneficiario -> {
            beneficiarioSelecionadoId = beneficiario.getId();
            jTextField1.setText(beneficiario.getNomeCompleto());
            jTextField2.setText(beneficiario.getNumeroBI());
            jTextField3.setText(beneficiario.getDataNascimento().toString());
            jTextField6.setText(beneficiario.getNuit());
            jComboBox3.setSelectedItem(beneficiario.getGenero().name());
            jComboBox4.setSelectedItem(beneficiario.getEstadoCivil().name());
            jTextField7.setText(beneficiario.getTelefone());
            jTextField8.setText(beneficiario.getEmail());
            jTextField9.setText(beneficiario.getEndereco());
            jComboBox1.setSelectedItem(beneficiario.getNacionalidade());
            jTextField10.setText(beneficiario.getProvincia());
            jTextField11.setText(beneficiario.getDistrito());
        }));
    }

    private void limparFormularioBeneficiario() {
        beneficiarioSelecionadoId = null;
        jTable2.clearSelection();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox1.setSelectedItem("Moçambicana");
    }

    private void executarAcaoCrud(Runnable acao) {
        try {
            acao.run();
        } catch (IllegalArgumentException | DateTimeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Dados inválidos", JOptionPane.WARNING_MESSAGE);
        } catch (java.util.NoSuchElementException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Registo não encontrado", JOptionPane.WARNING_MESSAGE);
        } catch (HibernateException | IllegalStateException ex) {
            logger.log(Level.SEVERE, "Falha ao aceder aos beneficiários.", ex);
            JOptionPane.showMessageDialog(this,
                    "Não foi possível aceder à base de dados: " + ex.getMessage(),
                    "Erro de persistência", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaPricipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel beneficio;
    private javax.swing.JButton beneficios;
    private javax.swing.JButton btnPensao;
    private javax.swing.JPanel cabesalho;
    private javax.swing.JPanel centro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pensao;
    // End of variables declaration//GEN-END:variables
}
